/**
 * cftExport.ts — CloudFormation Template (YAML) Generator
 *
 * Synthesizes deployable AWS CloudFormation YAML templates from the single-path
 * ServicePlan contract.
 *
 * Guarantees:
 * - Deterministic, closed-enum mapping table: AWS service key → CloudFormation
 *   resource type + minimal required properties (matching NPM_FRAMEWORK_MAP philosophy).
 * - Generates valid, deployable CFT YAML per pattern (serverless-rest-api,
 *   containerized-web-app, static-site-cdn, event-driven-pipeline,
 *   full-stack-serverless, worker-queue, data-pipeline, ml-pipeline, generic).
 * - Wires IAM roles, policies, and cross-resource links (Lambda ↔ API Gateway,
 *   CloudFront ↔ S3, Lambda ↔ SQS, ECS ↔ TaskExecutionRole).
 * - Parameterized with Environment (dev/staging/prod) and AppName.
 * - Decision 33 Disclaimer: "Starting template, not production-ready IaC."
 */

import { stringify, parse } from "yaml";
import type { ServicePlan, ServiceId } from "./schema.ts";

// ---------------------------------------------------------------------------
// Constants & Disclaimer
// ---------------------------------------------------------------------------

export const CFT_DISCLAIMER_COMMENT = `# ==============================================================================
# AWS CloudFormation Template — Generated by AWS Architect
#
# DISCLAIMER (Decision 33):
# This is a starting architectural template, not production-ready IaC.
# Review security groups, IAM least-privilege policies, CIDR allocations,
# storage encryption, and compute sizing before deploying to production.
# ==============================================================================
`;

export const CFT_DISCLAIMER_TEXT =
  "Starting architectural template, not production-ready IaC. Review security policies and sizing before deployment.";

// ---------------------------------------------------------------------------
// Resource Mapping Specifications
// ---------------------------------------------------------------------------

export interface CftContext {
  appName: string;
  environment: string;
  allServiceIds: Set<string>;
}

export interface CftServiceSpec {
  serviceId: string;
  primaryType: string;
  relatedTypes?: string[];
  description: string;
  generateResources: (ctx: CftContext) => Record<string, any>;
  generateOutputs?: (ctx: CftContext) => Record<string, any>;
}

/**
 * Closed-enum mapping table for AWS services to CloudFormation resources.
 * Deterministic mapping table philosophy (matches repoAnalyzer.ts mapping pattern).
 */
export const CFT_SERVICE_RESOURCE_MAP: Record<string, CftServiceSpec> = {
  Lambda: {
    serviceId: "Lambda",
    primaryType: "AWS::Lambda::Function",
    relatedTypes: ["AWS::IAM::Role", "AWS::Lambda::Permission", "AWS::Lambda::EventSourceMapping"],
    description: "AWS Lambda serverless compute function with IAM execution role",
    generateResources: (ctx) => {
      const resources: Record<string, any> = {
        LambdaExecutionRole: {
          Type: "AWS::IAM::Role",
          Properties: {
            RoleName: { "Fn::Sub": "${AppName}-${Environment}-lambda-role" },
            AssumeRolePolicyDocument: {
              Version: "2012-10-17",
              Statement: [
                {
                  Effect: "Allow",
                  Principal: { Service: "lambda.amazonaws.com" },
                  Action: "sts:AssumeRole",
                },
              ],
            },
            ManagedPolicyArns: [
              "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
            ],
          },
        },
        AppFunction: {
          Type: "AWS::Lambda::Function",
          Properties: {
            FunctionName: { "Fn::Sub": "${AppName}-${Environment}-fn" },
            Handler: "index.handler",
            Runtime: "nodejs20.x",
            Role: { "Fn::GetAtt": ["LambdaExecutionRole", "Arn"] },
            Code: {
              ZipFile: 'exports.handler = async () => ({ statusCode: 200, body: JSON.stringify({ message: "Hello from AWS Architect!" }) });',
            },
            Timeout: 30,
            MemorySize: 512,
            Description: "Serverless application handler generated by AWS Architect",
          },
        },
      };

      // Cross-resource integration: API Gateway permission
      if (ctx.allServiceIds.has("APIGateway")) {
        resources.LambdaApiGatewayPermission = {
          Type: "AWS::Lambda::Permission",
          Properties: {
            FunctionName: { Ref: "AppFunction" },
            Action: "lambda:InvokeFunction",
            Principal: "apigateway.amazonaws.com",
            SourceArn: {
              "Fn::Sub": "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*",
            },
          },
        };
      }

      // Cross-resource integration: SQS Event Source Mapping
      if (ctx.allServiceIds.has("SQS")) {
        resources.LambdaSqsTrigger = {
          Type: "AWS::Lambda::EventSourceMapping",
          Properties: {
            BatchSize: 10,
            Enabled: true,
            EventSourceArn: { "Fn::GetAtt": ["AppQueue", "Arn"] },
            FunctionName: { "Fn::GetAtt": ["AppFunction", "Arn"] },
          },
        };
      }

      return resources;
    },
    generateOutputs: () => ({
      FunctionArn: {
        Description: "ARN of the main application Lambda function",
        Value: { "Fn::GetAtt": ["AppFunction", "Arn"] },
      },
    }),
  },

  APIGateway: {
    serviceId: "APIGateway",
    primaryType: "AWS::ApiGatewayV2::Api",
    relatedTypes: ["AWS::ApiGatewayV2::Stage", "AWS::ApiGatewayV2::Integration", "AWS::ApiGatewayV2::Route"],
    description: "Amazon API Gateway HTTP API with auto-deploy stage",
    generateResources: (ctx) => {
      const resources: Record<string, any> = {
        HttpApi: {
          Type: "AWS::ApiGatewayV2::Api",
          Properties: {
            Name: { "Fn::Sub": "${AppName}-${Environment}-api" },
            ProtocolType: "HTTP",
            Description: "HTTP API Gateway endpoint generated by AWS Architect",
          },
        },
        HttpApiStage: {
          Type: "AWS::ApiGatewayV2::Stage",
          Properties: {
            ApiId: { Ref: "HttpApi" },
            StageName: { Ref: "Environment" },
            AutoDeploy: true,
          },
        },
      };

      if (ctx.allServiceIds.has("Lambda")) {
        resources.HttpApiLambdaIntegration = {
          Type: "AWS::ApiGatewayV2::Integration",
          Properties: {
            ApiId: { Ref: "HttpApi" },
            IntegrationType: "AWS_PROXY",
            IntegrationUri: { "Fn::GetAtt": ["AppFunction", "Arn"] },
            PayloadFormatVersion: "2.0",
          },
        };
        resources.HttpApiDefaultRoute = {
          Type: "AWS::ApiGatewayV2::Route",
          Properties: {
            ApiId: { Ref: "HttpApi" },
            RouteKey: "$default",
            Target: { "Fn::Sub": "integrations/${HttpApiLambdaIntegration}" },
          },
        };
      }

      return resources;
    },
    generateOutputs: () => ({
      ApiEndpoint: {
        Description: "HTTP API Gateway endpoint URL",
        Value: { "Fn::GetAtt": ["HttpApi", "ApiEndpoint"] },
      },
    }),
  },

  S3: {
    serviceId: "S3",
    primaryType: "AWS::S3::Bucket",
    description: "Amazon S3 encrypted object storage bucket with public access blocked",
    generateResources: () => ({
      AppBucket: {
        Type: "AWS::S3::Bucket",
        Properties: {
          BucketName: {
            "Fn::Sub": "${AppName}-${Environment}-storage-${AWS::AccountId}",
          },
          PublicAccessBlockConfiguration: {
            BlockPublicAcls: true,
            BlockPublicPolicy: true,
            IgnorePublicAcls: true,
            RestrictPublicBuckets: true,
          },
          BucketEncryption: {
            ServerSideEncryptionConfiguration: [
              {
                ServerSideEncryptionByDefault: {
                  SSEAlgorithm: "AES256",
                },
              },
            ],
          },
        },
      },
    }),
    generateOutputs: () => ({
      BucketName: {
        Description: "Name of the provisioned S3 bucket",
        Value: { Ref: "AppBucket" },
      },
      BucketDomainName: {
        Description: "Regional domain name of the S3 bucket",
        Value: { "Fn::GetAtt": ["AppBucket", "RegionalDomainName"] },
      },
    }),
  },

  CloudFront: {
    serviceId: "CloudFront",
    primaryType: "AWS::CloudFront::Distribution",
    description: "Amazon CloudFront CDN distribution with HTTPS redirection",
    generateResources: (ctx) => {
      const hasS3 = ctx.allServiceIds.has("S3");
      const originConfig = hasS3
        ? {
            Id: "S3Origin",
            DomainName: { "Fn::GetAtt": ["AppBucket", "RegionalDomainName"] },
            S3OriginConfig: {},
          }
        : {
            Id: "CustomOrigin",
            DomainName: "example.com",
            CustomOriginConfig: {
              HTTPPort: 80,
              HTTPSPort: 443,
              OriginProtocolPolicy: "https-only",
            },
          };

      return {
        CloudFrontDistribution: {
          Type: "AWS::CloudFront::Distribution",
          Properties: {
            DistributionConfig: {
              Enabled: true,
              DefaultRootObject: "index.html",
              Comment: { "Fn::Sub": "CDN distribution for ${AppName} (${Environment})" },
              Origins: [originConfig],
              DefaultCacheBehavior: {
                TargetOriginId: originConfig.Id,
                ViewerProtocolPolicy: "redirect-to-https",
                AllowedMethods: ["GET", "HEAD", "OPTIONS"],
                CachedMethods: ["GET", "HEAD"],
                ForwardedValues: {
                  QueryString: false,
                  Cookies: { Forward: "none" },
                },
              },
            },
          },
        },
      };
    },
    generateOutputs: () => ({
      DistributionDomainName: {
        Description: "CloudFront CDN domain name",
        Value: { "Fn::GetAtt": ["CloudFrontDistribution", "DomainName"] },
      },
    }),
  },

  DynamoDB: {
    serviceId: "DynamoDB",
    primaryType: "AWS::DynamoDB::Table",
    description: "Amazon DynamoDB on-demand NoSQL database table",
    generateResources: () => ({
      AppTable: {
        Type: "AWS::DynamoDB::Table",
        Properties: {
          TableName: { "Fn::Sub": "${AppName}-${Environment}-table" },
          BillingMode: "PAY_PER_REQUEST",
          AttributeDefinitions: [
            { AttributeName: "id", AttributeType: "S" },
          ],
          KeySchema: [
            { AttributeName: "id", KeyType: "HASH" },
          ],
          PointInTimeRecoverySpecification: {
            PointInTimeRecoveryEnabled: true,
          },
        },
      },
    }),
    generateOutputs: () => ({
      TableName: {
        Description: "DynamoDB table name",
        Value: { Ref: "AppTable" },
      },
      TableArn: {
        Description: "DynamoDB table ARN",
        Value: { "Fn::GetAtt": ["AppTable", "Arn"] },
      },
    }),
  },

  SQS: {
    serviceId: "SQS",
    primaryType: "AWS::SQS::Queue",
    description: "Amazon SQS standard message queue with dead-letter queue",
    generateResources: () => ({
      AppDeadLetterQueue: {
        Type: "AWS::SQS::Queue",
        Properties: {
          QueueName: { "Fn::Sub": "${AppName}-${Environment}-dlq" },
          MessageRetentionPeriod: 1209600,
        },
      },
      AppQueue: {
        Type: "AWS::SQS::Queue",
        Properties: {
          QueueName: { "Fn::Sub": "${AppName}-${Environment}-queue" },
          VisibilityTimeout: 300,
          RedrivePolicy: {
            deadLetterTargetArn: { "Fn::GetAtt": ["AppDeadLetterQueue", "Arn"] },
            maxReceiveCount: 5,
          },
        },
      },
    }),
    generateOutputs: () => ({
      QueueUrl: {
        Description: "URL of the primary SQS queue",
        Value: { Ref: "AppQueue" },
      },
      QueueArn: {
        Description: "ARN of the primary SQS queue",
        Value: { "Fn::GetAtt": ["AppQueue", "Arn"] },
      },
    }),
  },

  SNS: {
    serviceId: "SNS",
    primaryType: "AWS::SNS::Topic",
    description: "Amazon SNS pub/sub notification topic",
    generateResources: () => ({
      AppTopic: {
        Type: "AWS::SNS::Topic",
        Properties: {
          TopicName: { "Fn::Sub": "${AppName}-${Environment}-topic" },
          DisplayName: { "Fn::Sub": "${AppName} (${Environment}) notifications" },
        },
      },
    }),
    generateOutputs: () => ({
      TopicArn: {
        Description: "ARN of the SNS topic",
        Value: { Ref: "AppTopic" },
      },
    }),
  },

  EventBridge: {
    serviceId: "EventBridge",
    primaryType: "AWS::Events::EventBus",
    description: "Amazon EventBridge custom event bus",
    generateResources: () => ({
      AppEventBus: {
        Type: "AWS::Events::EventBus",
        Properties: {
          Name: { "Fn::Sub": "${AppName}-${Environment}-bus" },
        },
      },
    }),
    generateOutputs: () => ({
      EventBusArn: {
        Description: "ARN of the custom EventBridge bus",
        Value: { "Fn::GetAtt": ["AppEventBus", "Arn"] },
      },
    }),
  },

  ECS: {
    serviceId: "ECS",
    primaryType: "AWS::ECS::Cluster",
    relatedTypes: ["AWS::ECS::TaskDefinition", "AWS::ECS::Service", "AWS::IAM::Role"],
    description: "Amazon ECS Fargate cluster, task definition, and service",
    generateResources: (ctx) => {
      const hasVpc = ctx.allServiceIds.has("VPC");
      const networkConfig = hasVpc
        ? {
            AwsvpcConfiguration: {
              AssignPublicIp: "ENABLED",
              Subnets: [{ Ref: "PublicSubnet1" }],
            },
          }
        : undefined;

      const resources: Record<string, any> = {
        EcsCluster: {
          Type: "AWS::ECS::Cluster",
          Properties: {
            ClusterName: { "Fn::Sub": "${AppName}-${Environment}-cluster" },
          },
        },
        EcsTaskExecutionRole: {
          Type: "AWS::IAM::Role",
          Properties: {
            RoleName: { "Fn::Sub": "${AppName}-${Environment}-ecs-exec-role" },
            AssumeRolePolicyDocument: {
              Version: "2012-10-17",
              Statement: [
                {
                  Effect: "Allow",
                  Principal: { Service: "ecs-tasks.amazonaws.com" },
                  Action: "sts:AssumeRole",
                },
              ],
            },
            ManagedPolicyArns: [
              "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
            ],
          },
        },
        EcsTaskDefinition: {
          Type: "AWS::ECS::TaskDefinition",
          Properties: {
            Family: { "Fn::Sub": "${AppName}-${Environment}-task" },
            Cpu: "256",
            Memory: "512",
            NetworkMode: "awsvpc",
            RequiresCompatibilities: ["FARGATE"],
            ExecutionRoleArn: { "Fn::GetAtt": ["EcsTaskExecutionRole", "Arn"] },
            ContainerDefinitions: [
              {
                Name: "app",
                Image: "public.ecr.aws/docker/library/httpd:latest",
                PortMappings: [{ ContainerPort: 80 }],
              },
            ],
          },
        },
        EcsService: {
          Type: "AWS::ECS::Service",
          Properties: {
            ServiceName: { "Fn::Sub": "${AppName}-${Environment}-svc" },
            Cluster: { Ref: "EcsCluster" },
            TaskDefinition: { Ref: "EcsTaskDefinition" },
            DesiredCount: 1,
            LaunchType: "FARGATE",
            ...(networkConfig ? { NetworkConfiguration: networkConfig } : {}),
          },
        },
      };

      return resources;
    },
    generateOutputs: () => ({
      EcsClusterName: {
        Description: "Name of the ECS Cluster",
        Value: { Ref: "EcsCluster" },
      },
    }),
  },

  Fargate: {
    serviceId: "Fargate",
    primaryType: "AWS::ECS::Service",
    description: "Amazon ECS Fargate managed container service (mapped identically to ECS)",
    generateResources: (ctx) => CFT_SERVICE_RESOURCE_MAP.ECS.generateResources(ctx),
    generateOutputs: (ctx) => CFT_SERVICE_RESOURCE_MAP.ECS.generateOutputs?.(ctx) ?? {},
  },

  EC2: {
    serviceId: "EC2",
    primaryType: "AWS::EC2::Instance",
    relatedTypes: ["AWS::EC2::SecurityGroup"],
    description: "Amazon EC2 instance with security group",
    generateResources: (ctx) => {
      const hasVpc = ctx.allServiceIds.has("VPC");
      return {
        AppSecurityGroup: {
          Type: "AWS::EC2::SecurityGroup",
          Properties: {
            GroupDescription: { "Fn::Sub": "Security group for ${AppName} (${Environment})" },
            ...(hasVpc ? { VpcId: { Ref: "AppVpc" } } : {}),
            SecurityGroupIngress: [
              {
                IpProtocol: "tcp",
                FromPort: 80,
                ToPort: 80,
                CidrIp: "0.0.0.0/0",
              },
            ],
          },
        },
        AppInstance: {
          Type: "AWS::EC2::Instance",
          Properties: {
            InstanceType: "t3.small",
            SecurityGroupIds: [{ "Fn::GetAtt": ["AppSecurityGroup", "GroupId"] }],
            ...(hasVpc ? { SubnetId: { Ref: "PublicSubnet1" } } : {}),
            Tags: [
              { Key: "Name", Value: { "Fn::Sub": "${AppName}-${Environment}-ec2" } },
            ],
          },
        },
      };
    },
    generateOutputs: () => ({
      InstanceId: {
        Description: "EC2 instance ID",
        Value: { Ref: "AppInstance" },
      },
    }),
  },

  ALB: {
    serviceId: "ALB",
    primaryType: "AWS::ElasticLoadBalancingV2::LoadBalancer",
    relatedTypes: [
      "AWS::ElasticLoadBalancingV2::TargetGroup",
      "AWS::ElasticLoadBalancingV2::Listener",
    ],
    description: "Application Load Balancer with HTTP target group and listener",
    generateResources: (ctx) => {
      const hasVpc = ctx.allServiceIds.has("VPC");
      const subnets = hasVpc
        ? [{ Ref: "PublicSubnet1" }, { Ref: "PublicSubnet2" }]
        : [];

      return {
        AlbTargetGroup: {
          Type: "AWS::ElasticLoadBalancingV2::TargetGroup",
          Properties: {
            Name: { "Fn::Sub": "${AppName}-${Environment}-tg" },
            Port: 80,
            Protocol: "HTTP",
            TargetType: "ip",
            ...(hasVpc ? { VpcId: { Ref: "AppVpc" } } : {}),
          },
        },
        ApplicationLoadBalancer: {
          Type: "AWS::ElasticLoadBalancingV2::LoadBalancer",
          Properties: {
            Name: { "Fn::Sub": "${AppName}-${Environment}-alb" },
            Scheme: "internet-facing",
            Type: "application",
            ...(subnets.length > 0 ? { Subnets: subnets } : {}),
          },
        },
        AlbHttpListener: {
          Type: "AWS::ElasticLoadBalancingV2::Listener",
          Properties: {
            LoadBalancerArn: { Ref: "ApplicationLoadBalancer" },
            Port: 80,
            Protocol: "HTTP",
            DefaultActions: [
              {
                Type: "forward",
                TargetGroupArn: { Ref: "AlbTargetGroup" },
              },
            ],
          },
        },
      };
    },
    generateOutputs: () => ({
      LoadBalancerDns: {
        Description: "Public DNS name of the Application Load Balancer",
        Value: { "Fn::GetAtt": ["ApplicationLoadBalancer", "DNSName"] },
      },
    }),
  },

  VPC: {
    serviceId: "VPC",
    primaryType: "AWS::EC2::VPC",
    relatedTypes: [
      "AWS::EC2::Subnet",
      "AWS::EC2::InternetGateway",
      "AWS::EC2::VPCGatewayAttachment",
    ],
    description: "Amazon VPC with public subnets and internet gateway",
    generateResources: () => ({
      AppVpc: {
        Type: "AWS::EC2::VPC",
        Properties: {
          CidrBlock: "10.0.0.0/16",
          EnableDnsHostnames: true,
          EnableDnsSupport: true,
          Tags: [{ Key: "Name", Value: { "Fn::Sub": "${AppName}-${Environment}-vpc" } }],
        },
      },
      PublicSubnet1: {
        Type: "AWS::EC2::Subnet",
        Properties: {
          VpcId: { Ref: "AppVpc" },
          CidrBlock: "10.0.1.0/24",
          MapPublicIpOnLaunch: true,
          Tags: [{ Key: "Name", Value: { "Fn::Sub": "${AppName}-${Environment}-public-1" } }],
        },
      },
      PublicSubnet2: {
        Type: "AWS::EC2::Subnet",
        Properties: {
          VpcId: { Ref: "AppVpc" },
          CidrBlock: "10.0.2.0/24",
          MapPublicIpOnLaunch: true,
          Tags: [{ Key: "Name", Value: { "Fn::Sub": "${AppName}-${Environment}-public-2" } }],
        },
      },
      InternetGateway: {
        Type: "AWS::EC2::InternetGateway",
        Properties: {
          Tags: [{ Key: "Name", Value: { "Fn::Sub": "${AppName}-${Environment}-igw" } }],
        },
      },
      VpcGatewayAttachment: {
        Type: "AWS::EC2::VPCGatewayAttachment",
        Properties: {
          VpcId: { Ref: "AppVpc" },
          InternetGatewayId: { Ref: "InternetGateway" },
        },
      },
    }),
    generateOutputs: () => ({
      VpcId: {
        Description: "VPC ID",
        Value: { Ref: "AppVpc" },
      },
    }),
  },

  RDS: {
    serviceId: "RDS",
    primaryType: "AWS::RDS::DBInstance",
    description: "Amazon RDS relational database instance (MySQL)",
    generateResources: (ctx) => {
      const hasVpc = ctx.allServiceIds.has("VPC");
      const resources: Record<string, any> = {};

      if (hasVpc) {
        resources.DbSubnetGroup = {
          Type: "AWS::RDS::DBSubnetGroup",
          Properties: {
            DBSubnetGroupDescription: { "Fn::Sub": "Subnet group for ${AppName} (${Environment})" },
            SubnetIds: [{ Ref: "PublicSubnet1" }, { Ref: "PublicSubnet2" }],
          },
        };
      }

      resources.AppDatabase = {
        Type: "AWS::RDS::DBInstance",
        Properties: {
          DBInstanceIdentifier: { "Fn::Sub": "${AppName}-${Environment}-db" },
          AllocatedStorage: "20",
          DBInstanceClass: "db.t3.micro",
          Engine: "mysql",
          MasterUsername: "adminuser",
          MasterUserPassword: "MustBeChanged123!",
          PubliclyAccessible: false,
          DeleteAutomatedBackups: true,
          BackupRetentionPeriod: 7,
          ...(hasVpc ? { DBSubnetGroupName: { Ref: "DbSubnetGroup" } } : {}),
        },
      };

      return resources;
    },
    generateOutputs: () => ({
      DatabaseEndpoint: {
        Description: "RDS Database connection endpoint address",
        Value: { "Fn::GetAtt": ["AppDatabase", "Endpoint.Address"] },
      },
    }),
  },

  Aurora: {
    serviceId: "Aurora",
    primaryType: "AWS::RDS::DBCluster",
    relatedTypes: ["AWS::RDS::DBInstance"],
    description: "Amazon Aurora Serverless v2 PostgreSQL cluster",
    generateResources: () => ({
      AuroraCluster: {
        Type: "AWS::RDS::DBCluster",
        Properties: {
          DBClusterIdentifier: { "Fn::Sub": "${AppName}-${Environment}-aurora" },
          Engine: "aurora-postgresql",
          MasterUsername: "adminuser",
          MasterUserPassword: "MustBeChanged123!",
          ServerlessV2ScalingConfiguration: {
            MinCapacity: 0.5,
            MaxCapacity: 4,
          },
        },
      },
      AuroraInstance: {
        Type: "AWS::RDS::DBInstance",
        Properties: {
          DBClusterIdentifier: { Ref: "AuroraCluster" },
          DBInstanceClass: "db.serverless",
          Engine: "aurora-postgresql",
        },
      },
    }),
  },

  ElastiCache: {
    serviceId: "ElastiCache",
    primaryType: "AWS::ElastiCache::CacheCluster",
    description: "Amazon ElastiCache Redis cluster",
    generateResources: () => ({
      CacheCluster: {
        Type: "AWS::ElastiCache::CacheCluster",
        Properties: {
          ClusterName: { "Fn::Sub": "${AppName}-${Environment}-cache" },
          Engine: "redis",
          CacheNodeType: "cache.t3.micro",
          NumCacheNodes: 1,
        },
      },
    }),
  },

  Cognito: {
    serviceId: "Cognito",
    primaryType: "AWS::Cognito::UserPool",
    relatedTypes: ["AWS::Cognito::UserPoolClient"],
    description: "Amazon Cognito User Pool and Application Client",
    generateResources: () => ({
      CognitoUserPool: {
        Type: "AWS::Cognito::UserPool",
        Properties: {
          UserPoolName: { "Fn::Sub": "${AppName}-${Environment}-users" },
          AutoVerifiedAttributes: ["email"],
        },
      },
      CognitoUserPoolClient: {
        Type: "AWS::Cognito::UserPoolClient",
        Properties: {
          ClientName: { "Fn::Sub": "${AppName}-${Environment}-client" },
          UserPoolId: { Ref: "CognitoUserPool" },
          GenerateSecret: false,
        },
      },
    }),
    generateOutputs: () => ({
      UserPoolId: {
        Description: "ID of the Cognito User Pool",
        Value: { Ref: "CognitoUserPool" },
      },
      UserPoolClientId: {
        Description: "ID of the Cognito User Pool Client",
        Value: { Ref: "CognitoUserPoolClient" },
      },
    }),
  },

  CloudWatch: {
    serviceId: "CloudWatch",
    primaryType: "AWS::Logs::LogGroup",
    description: "Amazon CloudWatch Log Group for centralized application logs",
    generateResources: () => ({
      AppLogGroup: {
        Type: "AWS::Logs::LogGroup",
        Properties: {
          LogGroupName: { "Fn::Sub": "/aws/${AppName}/${Environment}" },
          RetentionInDays: 30,
        },
      },
    }),
  },

  Kinesis: {
    serviceId: "Kinesis",
    primaryType: "AWS::Kinesis::Stream",
    description: "Amazon Kinesis Data Stream",
    generateResources: () => ({
      AppStream: {
        Type: "AWS::Kinesis::Stream",
        Properties: {
          Name: { "Fn::Sub": "${AppName}-${Environment}-stream" },
          ShardCount: 1,
        },
      },
    }),
  },

  MSK: {
    serviceId: "MSK",
    primaryType: "AWS::MSK::Cluster",
    description: "Amazon Managed Streaming for Apache Kafka (MSK) cluster",
    generateResources: () => ({
      MskCluster: {
        Type: "AWS::MSK::Cluster",
        Properties: {
          ClusterName: { "Fn::Sub": "${AppName}-${Environment}-kafka" },
          KafkaVersion: "3.5.1",
          NumberOfBrokerNodes: 2,
          BrokerNodeGroupInfo: {
            InstanceType: "kafka.m5.large",
            ClientSubnets: [{ "Fn::Sub": "${AppName}-${Environment}-subnet-1" }, { "Fn::Sub": "${AppName}-${Environment}-subnet-2" }],
          },
        },
      },
    }),
  },

  ECR: {
    serviceId: "ECR",
    primaryType: "AWS::ECR::Repository",
    description: "Amazon Elastic Container Registry repository",
    generateResources: () => ({
      AppRepository: {
        Type: "AWS::ECR::Repository",
        Properties: {
          RepositoryName: { "Fn::Sub": "${AppName}-${Environment}-repo" },
          ImageScanningConfiguration: { ScanOnPush: true },
        },
      },
    }),
  },

  SecretsManager: {
    serviceId: "SecretsManager",
    primaryType: "AWS::SecretsManager::Secret",
    description: "AWS Secrets Manager secret store",
    generateResources: () => ({
      AppSecret: {
        Type: "AWS::SecretsManager::Secret",
        Properties: {
          Name: { "Fn::Sub": "${AppName}-${Environment}-secret" },
          Description: "Application credentials managed by AWS Architect",
        },
      },
    }),
  },

  Route53: {
    serviceId: "Route53",
    primaryType: "AWS::Route53::HostedZone",
    description: "Amazon Route 53 public hosted zone",
    generateResources: () => ({
      AppHostedZone: {
        Type: "AWS::Route53::HostedZone",
        Properties: {
          Name: { "Fn::Sub": "${AppName}-${Environment}.example.com" },
        },
      },
    }),
  },

  SageMaker: {
    serviceId: "SageMaker",
    primaryType: "AWS::SageMaker::Model",
    description: "Amazon SageMaker Machine Learning model definition",
    generateResources: () => ({
      SageMakerModel: {
        Type: "AWS::SageMaker::Model",
        Properties: {
          ModelName: { "Fn::Sub": "${AppName}-${Environment}-ml-model" },
          ExecutionRoleArn: "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess",
          PrimaryContainer: {
            Image: "763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.0-cpu-py310",
          },
        },
      },
    }),
  },

  OpenSearch: {
    serviceId: "OpenSearch",
    primaryType: "AWS::OpenSearchService::Domain",
    description: "Amazon OpenSearch Service search domain",
    generateResources: () => ({
      OpenSearchDomain: {
        Type: "AWS::OpenSearchService::Domain",
        Properties: {
          DomainName: { "Fn::Sub": "${AppName}-${Environment}-search" },
          EngineVersion: "OpenSearch_2.11",
          ClusterConfig: {
            InstanceType: "t3.small.search",
            InstanceCount: 1,
            DedicatedMasterEnabled: false,
            ZoneAwarenessEnabled: false,
          },
          EBSOptions: {
            EBSEnabled: true,
            VolumeType: "gp3",
            VolumeSize: 20,
          },
        },
      },
    }),
  },

  Redshift: {
    serviceId: "Redshift",
    primaryType: "AWS::Redshift::Cluster",
    description: "Amazon Redshift Data Warehouse cluster",
    generateResources: () => ({
      RedshiftCluster: {
        Type: "AWS::Redshift::Cluster",
        Properties: {
          ClusterIdentifier: { "Fn::Sub": "${AppName}-${Environment}-dw" },
          NodeType: "dc2.large",
          NumberOfNodes: 1,
          MasterUsername: "awsuser",
          MasterUserPassword: "MustBeChanged123!",
          DBName: "analytics",
        },
      },
    }),
  },

  WAF: {
    serviceId: "WAF",
    primaryType: "AWS::WAFv2::WebACL",
    description: "AWS WAF Web ACL firewall",
    generateResources: () => ({
      AppWebAcl: {
        Type: "AWS::WAFv2::WebACL",
        Properties: {
          Name: { "Fn::Sub": "${AppName}-${Environment}-waf" },
          Scope: "REGIONAL",
          DefaultAction: { Allow: {} },
          VisibilityConfig: {
            CloudWatchMetricsEnabled: true,
            MetricName: "WafMetrics",
            SampledRequestsEnabled: true,
          },
        },
      },
    }),
  },
};

// ---------------------------------------------------------------------------
// Pattern Canonical Defaults
// ---------------------------------------------------------------------------

/** Canonical service IDs for each of the 6 fixed patterns (plus variants) */
export const PATTERN_CANONICAL_SERVICES: Record<string, string[]> = {
  "serverless-rest-api": ["APIGateway", "Lambda", "DynamoDB", "CloudWatch"],
  "serverless-api": ["APIGateway", "Lambda", "DynamoDB", "CloudWatch"],
  "containerized-web-app": ["ALB", "ECS", "ECR", "VPC", "RDS", "CloudWatch"],
  "containerised-app": ["ALB", "ECS", "ECR", "VPC", "RDS", "CloudWatch"],
  "static-site-cdn": ["CloudFront", "S3", "Route53"],
  "static-site": ["CloudFront", "S3", "Route53"],
  "event-driven-pipeline": ["EventBridge", "SQS", "Lambda", "DynamoDB", "CloudWatch"],
  "event-driven": ["EventBridge", "SQS", "Lambda", "DynamoDB", "CloudWatch"],
  "full-stack-serverless": ["CloudFront", "S3", "APIGateway", "Lambda", "DynamoDB", "Cognito"],
  "worker-queue": ["SQS", "Lambda", "DynamoDB", "CloudWatch"],
  "data-pipeline": ["Kinesis", "S3", "Redshift", "CloudWatch"],
  "ml-pipeline": ["SageMaker", "S3", "CloudWatch"],
  generic: ["Lambda", "S3", "CloudWatch"],
};

// ---------------------------------------------------------------------------
// Main CFT Generator
// ---------------------------------------------------------------------------

export interface CftGeneratorOptions {
  appName?: string;
  environment?: string;
  patternOverride?: string;
}

/**
 * Generates an AWS CloudFormation YAML template from a single-path ServicePlan.
 *
 * @param plan      The inferred or merged ServicePlan contract
/**
 * Synthesizes deployable CloudFormation YAML string(s) from a ServicePlan or array of ServicePlans.
 * When passed an array of plans (1..N), returns an array of YAML strings.
 * When passed a single plan, returns a single YAML string.
 * Single-element arrays produce byte-identical output to single-path calls.
 */
export function generateCftYaml(
  plans: ServicePlan[],
  options?: CftGeneratorOptions
): string[];
export function generateCftYaml(
  plan: ServicePlan,
  options?: CftGeneratorOptions
): string;
export function generateCftYaml(
  planOrPlans: ServicePlan | ServicePlan[],
  options?: CftGeneratorOptions
): string | string[];
export function generateCftYaml(
  planOrPlans: ServicePlan | ServicePlan[],
  options?: CftGeneratorOptions
): string | string[] {
  if (Array.isArray(planOrPlans)) {
    return planOrPlans.map((p) => generateSingleCftYaml(p, options));
  }
  return generateSingleCftYaml(planOrPlans, options);
}

export function generateSingleCftYaml(
  plan: ServicePlan,
  options?: CftGeneratorOptions
): string {
  const appName = options?.appName || "aws-architect-app";
  const environment = options?.environment || "dev";
  const rawPattern = options?.patternOverride || plan.detectedPattern || "generic";
  const pattern = rawPattern.toLowerCase().trim();

  // Collect unique services present in the plan's awsMappings
  const mappedServices = new Set<string>();
  for (const m of plan.awsMappings) {
    if (CFT_SERVICE_RESOURCE_MAP[m.serviceId]) {
      mappedServices.add(m.serviceId);
    }
  }

  // If no services were mapped, fall back to canonical services for the pattern
  if (mappedServices.size === 0) {
    const canonical = PATTERN_CANONICAL_SERVICES[pattern] || PATTERN_CANONICAL_SERVICES.generic;
    for (const id of canonical) {
      if (CFT_SERVICE_RESOURCE_MAP[id]) {
        mappedServices.add(id);
      }
    }
  }

  return buildTemplateYaml(Array.from(mappedServices), pattern, appName, environment);
}

/**
 * Generates CFT YAML directly from an array of service IDs and pattern name.
 */
export function generateCftFromServices(
  pattern: string,
  serviceIds: string[],
  options?: CftGeneratorOptions
): string {
  const appName = options?.appName || "aws-architect-app";
  const environment = options?.environment || "dev";
  const safePattern = pattern.toLowerCase().trim();

  // If service list is empty, use canonical pattern defaults
  let services = serviceIds.filter((id) => CFT_SERVICE_RESOURCE_MAP[id]);
  if (services.length === 0) {
    services = PATTERN_CANONICAL_SERVICES[safePattern] || PATTERN_CANONICAL_SERVICES.generic;
  }

  return buildTemplateYaml(services, safePattern, appName, environment);
}

/**
 * Internal worker to construct and stringify the CloudFormation document.
 */
function buildTemplateYaml(
  serviceIds: string[],
  pattern: string,
  appName: string,
  environment: string
): string {
  const allServiceIds = new Set(serviceIds);
  const ctx: CftContext = { appName, environment, allServiceIds };

  // 1. Top-level metadata
  const doc: Record<string, any> = {
    AWSTemplateFormatVersion: "2010-09-09",
    Description: `AWS CloudFormation Template — Generated by AWS Architect for pattern "${pattern}". ${CFT_DISCLAIMER_TEXT}`,
    Parameters: {
      Environment: {
        Type: "String",
        Default: environment,
        AllowedValues: ["dev", "staging", "prod"],
        Description: "Deployment target environment name",
      },
      AppName: {
        Type: "String",
        Default: appName,
        Description: "Application name used for resource naming and tagging",
      },
    },
    Resources: {},
    Outputs: {},
  };

  // 2. Generate resources for every service
  for (const serviceId of serviceIds) {
    const spec = CFT_SERVICE_RESOURCE_MAP[serviceId];
    if (!spec) continue;

    const res = spec.generateResources(ctx);
    Object.assign(doc.Resources, res);

    if (spec.generateOutputs) {
      const outs = spec.generateOutputs(ctx);
      Object.assign(doc.Outputs, outs);
    }
  }

  // Ensure Resources is never empty
  if (Object.keys(doc.Resources).length === 0) {
    Object.assign(doc.Resources, CFT_SERVICE_RESOURCE_MAP.S3.generateResources(ctx));
  }

  // Clean empty Outputs
  if (Object.keys(doc.Outputs).length === 0) {
    delete doc.Outputs;
  }

  // Convert object to YAML string
  const yamlBody = stringify(doc, { indent: 2, lineWidth: 0 });

  return `${CFT_DISCLAIMER_COMMENT}\n${yamlBody}`;
}

// ---------------------------------------------------------------------------
// Diagram XML Extraction Helper
// ---------------------------------------------------------------------------

/** Reverse map from common label substrings / display names to canonical ServiceId */
const DISPLAY_NAME_TO_SERVICE_ID: Record<string, string> = {
  lambda: "Lambda",
  "aws lambda": "Lambda",
  "api gateway": "APIGateway",
  "amazon api gateway": "APIGateway",
  s3: "S3",
  "amazon s3": "S3",
  cloudfront: "CloudFront",
  "amazon cloudfront": "CloudFront",
  dynamodb: "DynamoDB",
  "amazon dynamodb": "DynamoDB",
  sqs: "SQS",
  "amazon sqs": "SQS",
  sns: "SNS",
  "amazon sns": "SNS",
  eventbridge: "EventBridge",
  "amazon eventbridge": "EventBridge",
  ecs: "ECS",
  "amazon ecs": "ECS",
  fargate: "Fargate",
  ec2: "EC2",
  "amazon ec2": "EC2",
  alb: "ALB",
  "application load balancer": "ALB",
  vpc: "VPC",
  rds: "RDS",
  "amazon rds": "RDS",
  aurora: "Aurora",
  elasticache: "ElastiCache",
  cognito: "Cognito",
  cloudwatch: "CloudWatch",
  kinesis: "Kinesis",
  ecr: "ECR",
  secretsmanager: "SecretsManager",
  route53: "Route53",
  sagemaker: "SageMaker",
  redshift: "Redshift",
  waf: "WAF",
};

/**
 * Extracts the detected pattern and list of AWS services from an mxGraph XML string.
 */
export function extractServicesFromDiagramXml(diagramXml: string): {
  pattern: string;
  serviceIds: string[];
} {
  const serviceIds = new Set<string>();

  // Extract pattern if present in XML comments or title
  const patternMatch = diagramXml.match(/pattern="([^"]+)"|<!-- Pattern: ([^ ]+) -->|detectedPattern="([^"]+)"/i);
  const pattern = (patternMatch?.[1] || patternMatch?.[2] || patternMatch?.[3] || "generic").toLowerCase();

  // Scan for node values matching AWS services
  const cellRegex = /<mxCell[^>]+value="([^"]+)"/g;
  let match: RegExpExecArray | null;
  while ((match = cellRegex.exec(diagramXml)) !== null) {
    const rawValue = match[1]
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .toLowerCase()
      .trim();

    for (const [key, serviceId] of Object.entries(DISPLAY_NAME_TO_SERVICE_ID)) {
      if (rawValue.includes(key)) {
        serviceIds.add(serviceId);
      }
    }
  }

  return {
    pattern,
    serviceIds: Array.from(serviceIds),
  };
}

/**
 * Generates CFT YAML directly from an existing draw.io diagram XML string.
 */
export function generateCftFromDiagramXml(
  diagramXml: string,
  fallbackPattern?: string
): string {
  const extracted = extractServicesFromDiagramXml(diagramXml);
  const pattern = fallbackPattern || extracted.pattern;
  return generateCftFromServices(pattern, extracted.serviceIds);
}

// ---------------------------------------------------------------------------
// CloudFormation Syntax & Structural Validator (cfn-lint equivalent)
// ---------------------------------------------------------------------------

export interface CftValidationResult {
  valid: boolean;
  errors: string[];
}

/**
 * Rigorously validates a generated CloudFormation YAML template.
 * Checks YAML well-formedness, AWS format version, parameter schemas,
 * resource types, logical IDs, and intrinsic function reference integrity.
 */
export function validateCloudFormationTemplate(yamlContent: string): CftValidationResult {
  const errors: string[] = [];

  let doc: any;
  try {
    doc = parse(yamlContent);
  } catch (err: any) {
    return { valid: false, errors: [`YAML parse error: ${err.message}`] };
  }

  if (!doc || typeof doc !== "object") {
    return { valid: false, errors: ["Template root is not a valid YAML object"] };
  }

  // 1. Template Format Version
  if (!doc.AWSTemplateFormatVersion) {
    errors.push("Missing required field: AWSTemplateFormatVersion");
  } else if (String(doc.AWSTemplateFormatVersion) !== "2010-09-09") {
    errors.push(`Invalid AWSTemplateFormatVersion: expected '2010-09-09', got '${doc.AWSTemplateFormatVersion}'`);
  }

  // 2. Description
  if (!doc.Description || typeof doc.Description !== "string") {
    errors.push("Missing or invalid Description");
  }

  // 3. Parameters
  const paramNames = new Set<string>();
  if (doc.Parameters) {
    if (typeof doc.Parameters !== "object") {
      errors.push("Parameters must be a map of parameter declarations");
    } else {
      for (const [pName, pVal] of Object.entries(doc.Parameters) as [string, any][]) {
        paramNames.add(pName);
        if (!pVal?.Type) {
          errors.push(`Parameter "${pName}" is missing required field: Type`);
        }
      }
    }
  }

  // 4. Resources
  const resourceNames = new Set<string>();
  if (!doc.Resources || typeof doc.Resources !== "object" || Object.keys(doc.Resources).length === 0) {
    errors.push("Missing or empty Resources section");
  } else {
    for (const [rId, rVal] of Object.entries(doc.Resources) as [string, any][]) {
      resourceNames.add(rId);

      // Logical ID format
      if (!/^[a-zA-Z0-9]+$/.test(rId)) {
        errors.push(`Invalid logical ID "${rId}": must contain alphanumeric characters only`);
      }

      // Resource Type format
      if (!rVal?.Type || typeof rVal.Type !== "string") {
        errors.push(`Resource "${rId}" is missing required field: Type`);
      } else if (!/^AWS::[a-zA-Z0-9]+::[a-zA-Z0-9]+$/.test(rVal.Type)) {
        errors.push(`Resource "${rId}" has invalid AWS type pattern: "${rVal.Type}"`);
      }

      // Properties
      if (rVal.Properties && typeof rVal.Properties !== "object") {
        errors.push(`Resource "${rId}" Properties must be an object`);
      }
    }
  }

  // 5. Reference Integrity (Ref & Fn::GetAtt)
  const pseudoParams = new Set([
    "AWS::AccountId",
    "AWS::NotificationARNs",
    "AWS::NoValue",
    "AWS::Partition",
    "AWS::Region",
    "AWS::StackId",
    "AWS::StackName",
    "AWS::URLSuffix",
  ]);

  function checkRefs(node: any, path: string): void {
    if (!node || typeof node !== "object") return;

    if (node.Ref !== undefined) {
      const refTarget = String(node.Ref);
      if (!paramNames.has(refTarget) && !resourceNames.has(refTarget) && !pseudoParams.has(refTarget)) {
        errors.push(`Dangling Ref at ${path}: "${refTarget}" is not a defined parameter, resource, or pseudo-parameter`);
      }
    }

    if (node["Fn::GetAtt"] !== undefined) {
      const target = node["Fn::GetAtt"];
      const targetResource = Array.isArray(target) ? target[0] : String(target).split(".")[0];
      if (!resourceNames.has(targetResource)) {
        errors.push(`Dangling Fn::GetAtt at ${path}: resource "${targetResource}" is not defined in Resources`);
      }
    }

    for (const [k, v] of Object.entries(node)) {
      checkRefs(v, `${path}.${k}`);
    }
  }

  if (doc.Resources) {
    checkRefs(doc.Resources, "Resources");
  }
  if (doc.Outputs) {
    checkRefs(doc.Outputs, "Outputs");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
